[package]
    name    = "mod-dev"
    version = "1.0.1"
    edition = "2021"

[dependencies]
    glob = "0.3.2"
    serde_json = "1.0.138"
    serde = { version = "1.0.217", features = [
        "derive",
    ] }
    zip = "2.2.2"
    walkdir = "2.5.0"
