name: Rust

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

permissions: write-all


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        cargo build --target aarch64-unknown-linux-gnu
        cargo build -r --target x86_64-pc-windows-gnu
    # - name: Run tests
    #   run: cargo test --verbose

    - name: List build artifacts
      run: ls -l ./target/release

    - name: "Create release"
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          ./target/release/mod-dev.exe
          ./target/release/mod-dev
